export const notificationSettingsCopy = {
  title: '알림 수신 설정',
  description: '알림을 켜거나 끄면 바로 저장됩니다.',
  checkingSession: '로그인 상태를 확인 중입니다.',
  loading: '알림 설정을 불러오는 중입니다.',
  loadError: '알림 설정을 불러오지 못했습니다.',
  retry: '다시 시도',
  empty: '설정할 알림이 없습니다.',
  all: '전체 알림',
  allToggleLabel: '전체 알림 변경',
  enabledCount: (enabled: number, total: number) =>
    `${total}개 중 ${enabled}개 켜짐`,
  groupToggleLabel: (name: string, isOpen: boolean) =>
    `${name} ${isOpen ? '접기' : '펼치기'}`,
  groupSwitchLabel: (name: string) => `${name} 전체 변경`,
  saveError: '알림 설정을 저장하지 못했습니다. 다시 시도해 주세요.',
  groups: {
    REVIEW_AND_FOLLOW: '리뷰와 팔로우',
    TASTING: '테이스팅',
    PROGRAM: '프로그램',
    NOTICE_AND_EVENT: '공지와 이벤트',
    MY_ACTIVITY: '내 활동',
  } as Record<string, string>,
  items: {
    REVIEW_COMMENT_CREATE: '내 리뷰에 달린 댓글',
    REVIEW_REPLY_CREATE: '리뷰 답글',
    REVIEW_LIKE_ADD: '내 리뷰에 달린 좋아요',
    FOLLOW_CREATE: '새 팔로워',
    FOLLOWING_REVIEW_CREATE: '팔로잉의 새 리뷰',
    REVIEW_FEATURE_SELECT: '리뷰 선정',
    TASTING_OPEN: '테이스팅 모집',
    TASTING_UPDATE: '테이스팅 변경',
    PROGRAM_OPEN: '새 프로그램',
    PROGRAM_UPDATE: '프로그램 변경',
    PROGRAM_RESULT_ANNOUNCE: '프로그램 결과',
    NOTICE_PUBLISH: '새 공지',
    CAMPAIGN_OPEN: '새 이벤트',
    HELP_ANSWER_CREATE: '문의 답변',
    REPORT_RESULT_ANNOUNCE: '신고 처리 결과',
    CONTENT_MODERATE: '콘텐츠 조치',
    ACCOUNT_STATUS_UPDATE: '계정 상태 변경',
    ALCOHOL_SUBMISSION_REVIEW: '주류 등록 검토 결과',
  } as Record<string, string>,
};
