export const CURATION_V2_SPEC_CODES = {
  RECOMMENDED_WHISKY: 'RECOMMENDED_WHISKY',
  WHISKY_PAIRING: 'WHISKY_PAIRING',
  WHISKY_TASTING_EVENT: 'WHISKY_TASTING_EVENT',
} as const;

export type CurationV2SpecCode =
  (typeof CURATION_V2_SPEC_CODES)[keyof typeof CURATION_V2_SPEC_CODES];
