window.BN = {
  pages: [
    ['home', '홈', '탐색'],
    ['explore', '둘러보기', '탐색'],
    ['whiskey', '위스키 상세', '탐색'],
    ['review', '리뷰 상세', '기록'],
    ['write', '리뷰 작성·수정', '기록'],
    ['profile', '프로필', '기록'],
    ['bottle', '마이보틀', '기록'],
    ['history', '나의 히스토리', '기록'],
    ['curation', '시음회·정보', '콘텐츠'],
    ['article', '시음회·큐레이션 상세', '콘텐츠'],
    ['imports', '수입통관', '콘텐츠'],
    ['import', '수입 정보 상세', '콘텐츠'],
    ['reviews', '위스키의 모든 리뷰', '보조'],
    ['importer', '수입사 상세', '보조'],
    ['settings', '설정', '보조'],
    ['login', '로그인 안내', '보조'],
    ['search', '검색 입력', '보조'],
    ['edit-profile', '프로필 수정', '보조'],
  ],
  bottles: [
    {
      id: 0,
      name: '크라이넬리쉬 14년 (구형)',
      en: 'CLYNELISH 14YO (OLD PACKAGING)',
      image: 'clynelish.webp',
      rating: 3.8,
      category: '싱글몰트',
      country: '스코틀랜드',
      region: '하이랜드',
      distillery: 'Clynelish',
      abv: '46%',
      age: '14년',
      intro:
        '말린 꽃과 꿀, 왁스를 연상시키는 향이 이어지는 하이랜드 싱글몰트 위스키입니다.',
      tags: ['말린 꽃', '꿀', '왁시한', '솔티'],
    },
    {
      id: 1,
      name: '스프링뱅크 10년',
      en: 'SPRINGBANK 10YO',
      image: 'springbank.jpg',
      rating: 3.8,
      category: '싱글몰트',
      country: '스코틀랜드',
      region: '캠벨타운',
      distillery: 'Springbank',
      abv: '46%',
      age: '10년',
      intro:
        '스프링뱅크 10년의 향과 맛을 기록하고 다른 사람들의 리뷰를 살펴보세요.',
      tags: ['오크', '몰트', '스모키'],
    },
    {
      id: 2,
      name: '야마자키 피티드 몰트 스패니시 오크',
      en: 'YAMAZAKI PEATED MALT SPANISH OAK',
      image: 'yamazaki.jpg',
      rating: 3.5,
      category: '싱글몰트',
      country: '일본',
      region: '오사카',
      distillery: 'Yamazaki',
      abv: null,
      age: null,
      intro:
        '야마자키의 다양한 향과 맛을 다른 사람들의 기록과 함께 살펴보세요.',
      tags: ['오크', '스모키'],
    },
    {
      id: 3,
      name: '마쓰이 돗토리 블렌디드 위스키',
      en: 'MATSUI TOTTORI BLENDED WHISKY',
      image: 'tottori.webp',
      rating: 0.5,
      category: '블렌디드',
      country: '일본',
      region: '돗토리',
      distillery: null,
      abv: null,
      age: null,
      intro: '이 위스키를 마셨던 순간을 별점과 리뷰로 남겨보세요.',
      tags: [],
    },
    {
      id: 4,
      name: 'E.H. 테일러 스몰 배치',
      en: 'E.H. TAYLOR SMALL BATCH',
      image: 'eh-taylor.webp',
      rating: 4.3,
      category: '아메리칸(버번)',
      country: '미국',
      region: '켄터키',
      distillery: 'Buffalo Trace',
      abv: '50%',
      age: null,
      intro: '오크와 바닐라를 떠올리게 하는 버번 위스키입니다.',
      tags: ['바닐라', '오크'],
    },
  ],
  categories: [
    ['싱글몰트', 'Single malt', 'singleMalt.png'],
    ['블렌디드 몰트', 'Blended malt', 'blendedMalt.png'],
    ['블렌디드', 'Blended', 'blended.png'],
    ['아메리칸(버번)', 'America (Bourbon)', 'america.png'],
    ['라이', 'Rye', 'rye.png'],
    ['기타', 'Other', 'other.png'],
  ],
  reviews: [
    {
      id: 0,
      bottle: 0,
      author: '오크향기',
      rating: 4.5,
      date: '2026.09.28',
      text: '말린 꽃과 꿀의 향이 먼저 느껴지고, 끝에는 짭조름한 여운이 남아요.\n\n조금씩 시간을 두고 마셔보니 오크 향도 느껴졌습니다. 다음에는 다른 잔으로도 비교해보고 싶어요.',
      tags: ['말린 꽃', '꿀', '오크'],
      price: 18000,
      unit: 'GLASS',
      place: '서울',
      likes: 2,
    },
    {
      id: 1,
      bottle: 1,
      author: '오늘의한잔',
      rating: 4,
      date: '2026.09.27',
      text: '오크와 바닐라가 부드럽게 이어지는 한 잔. 천천히 마시니 향이 더 풍부해졌어요.',
      tags: ['오크', '바닐라'],
      price: null,
      unit: 'GLASS',
      place: null,
      likes: 3,
    },
    {
      id: 2,
      bottle: 4,
      author: '잔의기록',
      rating: 4.5,
      date: '2026.09.25',
      text: '익숙한 바닐라 향 뒤로 묵직한 오크가 남았습니다. 얼음을 넣기 전과 후가 꽤 달랐어요.',
      tags: ['바닐라', '오크'],
      price: null,
      unit: 'BOTTLE',
      place: null,
      likes: 1,
    },
  ],
  articles: [
    {
      id: 0,
      type: '큐레이션',
      title: '가을의 위스키',
      image: 'banner-autumn.webp',
      subtitle: '따스함에서 서늘함으로 건너가는 시간',
      body: '선선해진 저녁, 천천히 한 잔을 마시며 위스키의 향을 살펴보세요. 익숙한 한 병에서도 온도와 시간에 따라 다른 인상을 발견할 수 있습니다.',
      bottles: [0, 1, 4],
    },
    {
      id: 1,
      type: '큐레이션',
      title: '보틀노트 매거진',
      image: 'banner-magazine.png',
      subtitle: '보틀노트 너머의 이야기',
      body: '위스키와 바, 그리고 한 잔을 함께하는 사람들의 이야기를 만나보세요.',
      bottles: [0, 2],
    },
    {
      id: 2,
      type: '시음회',
      title: '가을 위스키 시음회',
      image: 'banner-autumn.webp',
      subtitle: '서로 다른 세 가지 위스키를 비교하는 시간',
      body: '향과 맛을 비교하고, 각자의 인상을 나누는 시음회입니다. 세 가지 위스키를 천천히 살펴봅니다.',
      date: '2026.10.17 (토) 16:00',
      place: '서울 · 시음 공간',
      fee: '50,000원',
      bottles: [0, 1, 4],
    },
    {
      id: 3,
      type: '프로그램',
      title: '위스키 테이스팅 클래스',
      image: 'banner-magazine.png',
      subtitle: '한 잔을 기록하는 방법',
      body: '향을 맡고 맛을 살펴보는 기본 순서를 배우고 나만의 테이스팅 노트를 작성합니다.',
      date: '2026.10.24 (토) 15:00',
      place: '서울 · 클래스 공간',
      fee: '60,000원',
      bottles: [0, 1],
    },
  ],
};
