import { ExploreAlcohol, ExploreReview } from '@/types/Explore';

export const MOCK_ALCOHOL = [
  {
    alcoholId: 586,
    alcoholUrlImg:
      'https://d3dvjqqnb91j9d.cloudfront.net/alcohols/whisky/f7204d8e-bac5-42d1-b48c-cfe76cb9c169.jpg',
    korName: '롱로우 18년',
    engName: 'Longrow 18y',
    korCategory: '싱글 몰트',
    engCategory: 'Single Malt',
    korRegion: '스코틀랜드/캠벨타운',
    engRegion: 'Scotland/Campbeltown',
    cask: '100% Sherry',
    abv: '46',
    korDistillery: '스프링뱅크',
    engDistillery: 'Springbank',
    rating: 0.0,
    totalRatingsCount: 0,
    myRating: 0.0,
    myAvgRating: 0.0,
    isPicked: false,
    alcoholsTastingTags: [
      '사과',
      '칠리',
      '흙',
      '꿀',
      '훈제청어',
      '잎',
      '오트밀',
      '오일리',
      '오렌지',
      '피트',
      '후추',
      '스모키',
      '구운 고기',
      '스파이시',
      '우디',
    ],
  },
  {
    alcoholId: 594,
    alcoholUrlImg:
      'https://d3dvjqqnb91j9d.cloudfront.net/alcohols/whisky/0f2c9953-936c-425a-aca8-95dfb69588e3.jpg',
    korName: '레드브레스트 12년 캐스크 스트랭스',
    engName: 'Redbreast 12y Cask Strength',
    korCategory: '싱글 팟 스틸',
    engCategory: 'Single Pot Still',
    korRegion: '아일랜드',
    engRegion: 'Ireland',
    cask: 'Bourbon & Sherry',
    abv: '58.1',
    korDistillery: '미들턴',
    engDistillery: 'Midleton (1975-)',
    rating: 0.0,
    totalRatingsCount: 0,
    myRating: 0.0,
    myAvgRating: 0.0,
    isPicked: false,
    alcoholsTastingTags: [
      '보리',
      '크리미',
      '과일',
      '오크',
      '오렌지',
      '복숭아',
      '자두',
      '향신료',
      '핵과일',
      '술타나',
      '바닐라',
    ],
  },
  {
    alcoholId: 593,
    alcoholUrlImg:
      'https://d3dvjqqnb91j9d.cloudfront.net/alcohols/whisky/6ce7c007-4efa-4487-a74a-a324b5a50495.jpg',
    korName: '레드브레스트 15년',
    engName: 'Redbreast 15y',
    korCategory: '싱글 팟 스틸',
    engCategory: 'Single Pot Still',
    korRegion: '아일랜드',
    engRegion: 'Ireland',
    cask: 'Oloroso Sherry Butts, Bourbon Barrels',
    abv: '46',
    korDistillery: '미들턴',
    engDistillery: 'Midleton (1975-)',
    rating: 0.0,
    totalRatingsCount: 0,
    myRating: 0.0,
    myAvgRating: 0.0,
    isPicked: false,
    alcoholsTastingTags: [
      '바나나',
      '커피',
      '버터스카치',
      '카라멜',
      '시트러스',
      '크리미',
      '커스터드',
      '과일',
      '포도',
      '구아바',
      '건조된 풀',
      '꿀',
      '민트',
      '넛맥',
      '오렌지',
      '부드러운',
      '열대과일',
      '제스트',
    ],
  },
  {
    alcoholId: 592,
    alcoholUrlImg:
      'https://d3dvjqqnb91j9d.cloudfront.net/alcohols/whisky/e42d2e00-82a7-4bb4-8913-b4865653854e.jpg',
    korName: '레드브레스트 21년',
    engName: 'Redbreast 21y',
    korCategory: '싱글 팟 스틸',
    engCategory: 'Single Pot Still',
    korRegion: '아일랜드',
    engRegion: 'Ireland',
    cask: 'Oloroso Sherry Casks + Bourbon Barrels',
    abv: '46',
    korDistillery: '미들턴',
    engDistillery: 'Midleton (1975-)',
    rating: 0.0,
    totalRatingsCount: 0,
    myRating: 0.0,
    myAvgRating: 0.0,
    isPicked: false,
    alcoholsTastingTags: [
      '사과',
      '보리',
      '시트러스',
      '가죽',
      '민트',
      '땅콩',
      '파인애플',
      '건자두',
      '스파이시',
    ],
  },
  {
    alcoholId: 591,
    alcoholUrlImg:
      'https://d3dvjqqnb91j9d.cloudfront.net/alcohols/whisky/f15f67e4-144f-495a-883e-a26c99be54f3.jpg',
    korName: '레드브레스트 27년',
    engName: 'Redbreast 27y',
    korCategory: '싱글 팟 스틸',
    engCategory: 'Single Pot Still',
    korRegion: '아일랜드',
    engRegion: 'Ireland',
    cask: 'Bourbon, Sherry and Ruby Port',
    abv: '53.6',
    korDistillery: '미들턴',
    engDistillery: 'Midleton (1975-)',
    rating: 0.0,
    totalRatingsCount: 0,
    myRating: 0.0,
    myAvgRating: 0.0,
    isPicked: false,
    alcoholsTastingTags: [
      '사과',
      '바나나',
      '베리',
      '칠리',
      '시트러스',
      '코코넛',
      '흙',
      '무화과',
      '포도',
      '구아바',
      '허브',
      '꿀',
      '가죽',
      '망고',
      '민트',
      '넛맥',
      '견과류',
      '파인애플',
      '자두',
      '향신료',
      '토피',
      '열대과일',
      '바닐라',
      '월넛',
    ],
  },
  {
    alcoholId: 590,
    alcoholUrlImg:
      'https://d3dvjqqnb91j9d.cloudfront.net/alcohols/whisky/6b880fca-ed91-4c88-b83d-2448e9564285.jpg',
    korName: '로얄 브라클라 12년',
    engName: 'Royal Brackla 12y Oloroso Sherry Cask Finish',
    korCategory: '싱글 몰트',
    engCategory: 'Single Malt',
    korRegion: '스코트랜드/하이랜드',
    engRegion: 'Scotland/Highlands',
    cask: 'Oloroso Sherry Finish',
    abv: '46',
    korDistillery: '로얄 브라클라',
    engDistillery: 'Royal Brackla',
    rating: 0.0,
    totalRatingsCount: 0,
    myRating: 0.0,
    myAvgRating: 0.0,
    isPicked: false,
    alcoholsTastingTags: [
      '아몬드',
      '베리',
      '흑설탕',
      '케이크',
      '설탕에 볶은 견과류',
      '체리',
      '초콜렛',
      '말린 살구',
      '과일',
      '맥아',
      '복숭아',
      '핵과일',
      '달콤한',
    ],
  },
  {
    alcoholId: 589,
    alcoholUrlImg:
      'https://d3dvjqqnb91j9d.cloudfront.net/alcohols/whisky/70703fa8-039d-4ac6-8909-34f2c47b0a2f.jpg',
    korName: '로얄 브라클라 18년',
    engName: 'Royal Brackla 18y Palo Cortado Sherry Cask Finish',
    korCategory: '싱글 몰트',
    engCategory: 'Single Malt',
    korRegion: '스코트랜드/하이랜드',
    engRegion: 'Scotland/Highlands',
    cask: 'Palo Cortado Finish',
    abv: '46',
    korDistillery: '로얄 브라클라',
    engDistillery: 'Royal Brackla',
    rating: 0.0,
    totalRatingsCount: 0,
    myRating: 0.0,
    myAvgRating: 0.0,
    isPicked: false,
    alcoholsTastingTags: [
      '초콜렛살구',
      '보리',
      '비스킷',
      '크리미',
      '다크초콜릿',
      '과일',
      '오크',
      '오렌지',
      '복숭아',
      '자두',
      '건포도',
      '술타나',
      '바닐라',
    ],
  },
  {
    alcoholId: 588,
    alcoholUrlImg:
      'https://d3dvjqqnb91j9d.cloudfront.net/alcohols/whisky/513ea6ba-8d65-4ac5-ac65-a0af82894ab9.jpg',
    korName: '로얄 브라클라 21년',
    engName: 'Royal Brackla 21y Sherry Cask Finish',
    korCategory: '싱글 몰트',
    engCategory: 'Single Malt',
    korRegion: '스코트랜드/하이랜드',
    engRegion: 'Scotland/Highlands',
    cask: 'Oloroso, Palo Cortado & Pedro Ximénez Sherry',
    abv: '46',
    korDistillery: '로얄 브라클라',
    engDistillery: 'Royal Brackla',
    rating: 0.0,
    totalRatingsCount: 0,
    myRating: 0.0,
    myAvgRating: 0.0,
    isPicked: false,
    alcoholsTastingTags: [
      '사과',
      '과일',
      '허브',
      '멜론',
      '민트',
      '쉐리와인',
      '향신료',
      '스파이시',
      '우디',
    ],
  },
  {
    alcoholId: 587,
    alcoholUrlImg:
      'https://d3dvjqqnb91j9d.cloudfront.net/alcohols/whisky/3962154d-0852-4156-8d76-8a39d421e85b.jpg',
    korName: '롱로우 11년 타우니 포트 캐스크',
    engName: 'Longrow 11y Tawny Port Cask Matured',
    korCategory: '싱글 몰트',
    engCategory: 'Single Malt',
    korRegion: '스코틀랜드/캠벨타운',
    engRegion: 'Scotland/Campbeltown',
    cask: '7y BBrl, 4y Fresh Tawny Port Barrels',
    abv: '57.5',
    korDistillery: '스프링뱅크',
    engDistillery: 'Springbank',
    rating: 0.0,
    totalRatingsCount: 0,
    myRating: 0.0,
    myAvgRating: 0.0,
    isPicked: false,
    alcoholsTastingTags: [
      '아몬드',
      '재',
      '블랙베리',
      '체리',
      '시트러스',
      '과일',
      '꿀',
      '넛맥',
      '피트',
      '스모키',
    ],
  },
  {
    alcoholId: 579,
    alcoholUrlImg:
      'https://d3dvjqqnb91j9d.cloudfront.net/alcohols/whisky/0416c346-479a-4533-8509-72de56d3f8a9.jpg',
    korName: '맥캘란 18년 트리플캐스크',
    engName: 'Macallan 18y Triple Cask',
    korCategory: '싱글 몰트',
    engCategory: 'Single Malt',
    korRegion: '스코틀랜드/스페이사이드 ',
    engRegion: 'Scotland/Speyside',
    cask: 'Triple Casks',
    abv: '43',
    korDistillery: '맥캘란',
    engDistillery: 'Macallan',
    rating: 0.0,
    totalRatingsCount: 0,
    myRating: 0.0,
    myAvgRating: 0.0,
    isPicked: false,
    alcoholsTastingTags: [
      '알콜',
      '초콜렛살구',
      '허브의 쓴 맛',
      '시트러스',
      '과일',
      '허브',
      '오크',
      '복숭아',
      '부드러운',
      '간장',
      '향신료',
      '바닐라',
    ],
  },
] satisfies ExploreAlcohol[];

export const MOCK_REVIEW = [
  {
    userInfo: {
      userId: 35,
      nickName: '에바',
      userProfileImage: null,
    },
    isMyReview: false,
    alcoholId: 209,
    alcoholName: '글렌모렌지 시그넷',
    reviewId: 11,
    reviewContent:
      '커피향이 나서 신기해요. 부드럽고 비싼만큼 맛있습니다. 막입도 깊은 맛과 향을 느낄 수 있어요!',
    reviewRating: 5.0,
    reviewTags: ['커피'],
    createAt: '2025-05-18T19:32:45',
    modifiedAt: '2025-05-18T19:32:45',
    totalImageCount: 0,
    reviewImages: [],
    isBestReview: false,
    likeCount: 0,
    isLikedByMe: false,
    replyCount: 0,
    hasReplyByMe: false,
  },
  {
    userInfo: {
      userId: 34,
      nickName: '황금빛조니워커7',
      userProfileImage: null,
    },
    isMyReview: false,
    alcoholId: 209,
    alcoholName: '글렌모렌지 시그넷',
    reviewId: 7,
    reviewContent: '면세점에서 꼭 사야함',
    reviewRating: 5.0,
    reviewTags: ['약간 신맛', '커피향'],
    createAt: '2025-05-12T04:41:37',
    modifiedAt: '2025-05-15T01:52:29',
    totalImageCount: 3,
    reviewImages: [
      'https://dzjkrmkt5t9bn.cloudfront.net/review/20250515/1-15e23c1e-2b31-4a06-9690-334a5bb1270f.jpg',
      'https://dzjkrmkt5t9bn.cloudfront.net/review/20250515/2-74bf6c77-4cc0-4c2e-b767-bc22a7f61ce2.jpg',
      'https://dzjkrmkt5t9bn.cloudfront.net/review/20250515/3-39090ab1-0ea8-423e-8e32-ea71f92a540f.jpg',
    ],
    isBestReview: false,
    likeCount: 1,
    isLikedByMe: false,
    replyCount: 0,
    hasReplyByMe: false,
  },
  {
    userInfo: {
      userId: 34,
      nickName: '황금빛조니워커7',
      userProfileImage: null,
    },
    isMyReview: false,
    alcoholId: 43,
    alcoholName: '스터닝 카오스',
    reviewId: 10,
    reviewContent: '22,000원 미만이면 꼭 한 잔씩 마십니다 ',
    reviewRating: 3.0,
    reviewTags: [],
    createAt: '2025-05-13T22:24:16',
    modifiedAt: '2025-05-13T22:24:16',
    totalImageCount: 0,
    reviewImages: [],
    isBestReview: true,
    likeCount: 0,
    isLikedByMe: false,
    replyCount: 0,
    hasReplyByMe: false,
  },
  {
    userInfo: {
      userId: 4,
      nickName: '스모키한바텐더4',
      userProfileImage: null,
    },
    isMyReview: false,
    alcoholId: 209,
    alcoholName: '글렌모렌지 시그넷',
    reviewId: 9,
    reviewContent:
      '일본에 여행 갔다가 사왔는데\n처음에는 커피향도 안느껴지고 뭔가.. 했는데\n이젠 커피향도 잘 느껴지고 신기해요!!',
    reviewRating: 4.5,
    reviewTags: ['커피'],
    createAt: '2025-05-13T21:39:22',
    modifiedAt: '2025-05-13T21:39:22',
    totalImageCount: 3,
    reviewImages: [
      'https://dzjkrmkt5t9bn.cloudfront.net/review/20250513/1-fd45d330-bf24-4a54-a6ad-9f022819aff5.jpg',
      'https://dzjkrmkt5t9bn.cloudfront.net/review/20250513/2-2f37de9e-6d82-4325-9dd5-9d88d6fc581f.jpg',
      'https://dzjkrmkt5t9bn.cloudfront.net/review/20250513/3-be5a28b5-b129-4ed4-91a5-3b368df903fb.jpg',
    ],
    isBestReview: true,
    likeCount: 2,
    isLikedByMe: false,
    replyCount: 5,
    hasReplyByMe: false,
  },
  {
    userInfo: {
      userId: 36,
      nickName: '강렬한싱글몰트9',
      userProfileImage: null,
    },
    isMyReview: false,
    alcoholId: 209,
    alcoholName: '글렌모렌지 시그넷',
    reviewId: 8,
    reviewContent: '마싯서잉',
    reviewRating: 0.0,
    reviewTags: [],
    createAt: '2025-05-13T21:22:38',
    modifiedAt: '2025-05-13T21:22:38',
    totalImageCount: 0,
    reviewImages: [],
    isBestReview: false,
    likeCount: 0,
    isLikedByMe: false,
    replyCount: 0,
    hasReplyByMe: false,
  },
  {
    userInfo: {
      userId: 5,
      nickName: '황금빛글렌피딕5',
      userProfileImage: null,
    },
    isMyReview: false,
    alcoholId: 210,
    alcoholName: '글렌모렌지 넥타도르',
    reviewId: 6,
    reviewContent: '적당히 달고 적당히 무거운 밸런스가 좋은 위스키같아요.',
    reviewRating: 3.0,
    reviewTags: [],
    createAt: '2025-05-10T11:01:36',
    modifiedAt: '2025-05-10T11:01:36',
    totalImageCount: 0,
    reviewImages: [],
    isBestReview: true,
    likeCount: 0,
    isLikedByMe: false,
    replyCount: 0,
    hasReplyByMe: false,
  },
  {
    userInfo: {
      userId: 5,
      nickName: '황금빛글렌피딕5',
      userProfileImage: null,
    },
    isMyReview: false,
    alcoholId: 193,
    alcoholName: '하쿠슈 디스틸러 리저브',
    reviewId: 5,
    reviewContent: '제 취향은 아니었어요.. 묘한 아저씨 술 같은 느낌',
    reviewRating: 1.5,
    reviewTags: [],
    createAt: '2025-05-10T10:59:42',
    modifiedAt: '2025-05-10T10:59:42',
    totalImageCount: 0,
    reviewImages: [],
    isBestReview: true,
    likeCount: 0,
    isLikedByMe: false,
    replyCount: 0,
    hasReplyByMe: false,
  },
  {
    userInfo: {
      userId: 5,
      nickName: '황금빛글렌피딕5',
      userProfileImage: null,
    },
    isMyReview: false,
    alcoholId: 209,
    alcoholName: '글렌모렌지 시그넷',
    reviewId: 4,
    reviewContent: '부드럽고 깊은 풍미가 일품. 조금만 더 저렴하면 좋겠다.',
    reviewRating: 5.0,
    reviewTags: ['바닐라', '커피'],
    createAt: '2025-05-10T10:58:15',
    modifiedAt: '2025-05-10T10:58:15',
    totalImageCount: 0,
    reviewImages: [],
    isBestReview: false,
    likeCount: 2,
    isLikedByMe: false,
    replyCount: 0,
    hasReplyByMe: false,
  },
  {
    userInfo: {
      userId: 5,
      nickName: '황금빛글렌피딕5',
      userProfileImage: null,
    },
    isMyReview: false,
    alcoholId: 429,
    alcoholName: '오켄토션 12년',
    reviewId: 3,
    reviewContent: '독특한 술을 찾는다면 추천..',
    reviewRating: 2.0,
    reviewTags: [],
    createAt: '2025-05-10T10:57:25',
    modifiedAt: '2025-05-10T10:57:25',
    totalImageCount: 0,
    reviewImages: [],
    isBestReview: true,
    likeCount: 0,
    isLikedByMe: false,
    replyCount: 0,
    hasReplyByMe: false,
  },
  {
    userInfo: {
      userId: 5,
      nickName: '황금빛글렌피딕5',
      userProfileImage: null,
    },
    isMyReview: false,
    alcoholId: 278,
    alcoholName: '글렌알라키 12년 (24년 신형)',
    reviewId: 2,
    reviewContent: '달콤한 과일 향이 나서 맛있어요.',
    reviewRating: 5.0,
    reviewTags: ['건과일'],
    createAt: '2025-05-10T10:55:49',
    modifiedAt: '2025-05-10T10:56:35',
    totalImageCount: 1,
    reviewImages: [
      'https://dzjkrmkt5t9bn.cloudfront.net/review/20250510/1-bdce7de4-50a7-44e8-8408-fc9979c29856.jpg',
    ],
    isBestReview: true,
    likeCount: 0,
    isLikedByMe: false,
    replyCount: 0,
    hasReplyByMe: false,
  },
] satisfies ExploreReview[];
