name: Deploy Workflow

on:
  push:
    branches:
      - dev-depoly-check
  pull_request:
    types: [ closed ]
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      ## 원격 환경에 코드 복사
      - name: copy project
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          remote_path: /home/bottlenote/app/bottle-note-front-server
          remote_host: ${{ secrets.DEV_SERVER_IP }}
          remote_port: ${{ secrets.DEV_SERVER_HOST }}
          remote_user: bottlenote
          remote_key: ${{ secrets.DEV_SSH_KEY }}

      - name: deploy setup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          port: ${{ secrets.DEV_SERVER_HOST }}
          username: bottlenote
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/bottlenote/app/bottle-note-front-server
            touch  /home/bottlenote/app/bottle-note-front-server/.env
            echo "${{ secrets.ENV }}" > .env  

      - name: docker compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          port: ${{ secrets.DEV_SERVER_HOST }}
          username: bottlenote
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/bottlenote/app/bottle-note-front-server
            docker stop bottle-note-front-server || true
            docker rm bottle-note-front-server || true
            docker compose up -d --no-deps --build 
            docker image prune -f
